export const text = {
  LEARNING: 'Learning',
  TESTS: 'Tests',
  RAY: 'Ray Driving Theory',
  HOME: 'Home',
  PLAN: 'Your plan',
  LEADERBOARD: 'Leaderboard',
  PROFILE: 'Profile',
  CATEGORY: 'Category',
  QUESTIONS_OUT: 'questions out of',
  PASSED: 'passed',
  DVSA: 'DVSA Exam',
  EXPRESS: 'Express mode',
  HAZARD: 'Hazard perception',
  ROAD: 'Road signs',
  MULTIPLAYER: 'Multiplayer',
  MISTAKES: 'Mistakes',
  STATICTICS: 'Statistics',
  HIGHWAY: 'Highway',
  CODE: 'Code',
  FAVORITES: 'Favorites'
}
